/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Domain.Lista;
import Domain.Pelicula;
import com.opencsv.CSVReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Arrays;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Josec
 */
public class VentanaArchivo extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaArchivo
     */
    private JFileChooser jfileChooser;
    public Lista[] vectorListas;
    public static final char SEPARATOR=',';
    public static final char QUOTE='"';
    
    public VentanaArchivo(Lista[] vectorListas) {
        initComponents();
        this.vectorListas=vectorListas;
        btnLlenarListas.setEnabled(false);
    }
    
    private Lista[] llenarListas() throws IOException{
        CSVReader reader = null;
      try {
         reader = new CSVReader(new FileReader(jtfRuta.getText()),SEPARATOR,QUOTE);
         String[] nextLine=null;
         nextLine = reader.readNext();
         
         while ((nextLine = reader.readNext()) != null) {
             Pelicula pelicula=new Pelicula(nextLine[0],nextLine[1],nextLine[2],nextLine[3],nextLine[4],nextLine[5]);
                if(pelicula.getGenero().equals(this.vectorListas[0].getGenero()))
                    this.vectorListas[0].ingresarPelicula(pelicula);
                else if(pelicula.getGenero().equals(this.vectorListas[1].getGenero()))
                    this.vectorListas[1].ingresarPelicula(pelicula);
                else if(pelicula.getGenero().equals(this.vectorListas[2].getGenero()))
                    this.vectorListas[2].ingresarPelicula(pelicula);
                else if(pelicula.getGenero().equals(this.vectorListas[3].getGenero()))
                    this.vectorListas[3].ingresarPelicula(pelicula);
                else if(pelicula.getGenero().equals(this.vectorListas[4].getGenero()))
                    this.vectorListas[4].ingresarPelicula(pelicula);
                else
                    this.vectorListas[5].ingresarPelicula(pelicula);
                System.out.println(pelicula);
         }
         
      } catch (Exception e) {
      } finally {
         if (null != reader) {
            reader.close();
         } 
      }
        return vectorListas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfRuta = new javax.swing.JTextField();
        btnBuscarArchivo = new javax.swing.JButton();
        btnLlenarListas = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        btnBuscarArchivo.setText("Buscar Archivo");
        btnBuscarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarArchivoActionPerformed(evt);
            }
        });

        btnLlenarListas.setText("Llenar listas");
        btnLlenarListas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLlenarListasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnBuscarArchivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(btnLlenarListas)
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfRuta)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jtfRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLlenarListas)
                    .addComponent(btnBuscarArchivo))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarArchivoActionPerformed

        this.jfileChooser = new JFileChooser();
        this.jfileChooser.showOpenDialog(null);
        File file = jfileChooser.getSelectedFile();
        String ruta = jfileChooser.getSelectedFile()+"";
        VentanaPrincipal.ruta=ruta;
        
        if(ruta.indexOf(".csv")<0){
            JOptionPane.showMessageDialog(rootPane,"Archivo invalido");
        }
        else{
            jtfRuta.setText(ruta);
            btnLlenarListas.setEnabled(true);
        }
    }//GEN-LAST:event_btnBuscarArchivoActionPerformed

    private void btnLlenarListasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLlenarListasActionPerformed
        try {
            VentanaPrincipal.vectorListas=llenarListas();
        } catch (IOException ex) {
            Logger.getLogger(VentanaArchivo.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(rootPane, "Archivo Cargado en las listas");
    }//GEN-LAST:event_btnLlenarListasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarArchivo;
    private javax.swing.JButton btnLlenarListas;
    private javax.swing.JTextField jtfRuta;
    // End of variables declaration//GEN-END:variables
}
